// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsmcnazuhfugzsxbpgqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbWNuYXp1aGZ1Z3pzeGJwZ3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjI0NjgsImV4cCI6MjA2NzA5ODQ2OH0.hAi8fMEgRZ710aRvF7cTMxT84dZkNCZLoBoM78pEglg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'shiksha-check-app'
    }
  }
});